[.text-center]
image::https://twitch4j.github.io/assets/images/logo.svg[Logo,256,256,link="https://twitch4j.github.io/"]
image::https://img.shields.io/github/release/twitch4j/twitch4j/all.svg?style=?style=flat-square&label=latest[link="https://github.com/twitch4j/twitch4j/releases/latest"]
image::https://img.shields.io/github/workflow/status/twitch4j/twitch4j/ci?label=CI&logo=github&style=?style=flat-square&logo=github[GitHub Workflow Status,link="https://github.com/twitch4j/twitch4j/actions/workflows/ci.yml"]
image::https://img.shields.io/badge/wiki-Latest-green.svg?style=?style=flat-square&logo=read-the-docs[link="https://twitch4j.github.io/docs/"]
image::https://img.shields.io/discord/143001431388061696?color=7289DA&label=discord&logo=discord&logoColor=FFFFFF&style=?style=flat-square&logo=dicord[Discord,link="https://discord.gg/FQ5vgW3"]
image::https://img.shields.io/maven-central/v/com.github.twitch4j/twitch4j-common?logo=apache-maven&style=flat-square[Maven Central,link="https://search.maven.org/search?q=g:com.github.twitch4j"]
image::https://img.shields.io/badge/%20%20%F0%9F%93%A6%F0%9F%9A%80-semantic--release-e10079.svg?style=flat-square[link="https://github.com/semantic-release/semantic-release"]

== Java API for https://www.twitch.tv/[Twitch]

Welcome to the Javadoc.
Please refer to our https://twitch4j.github.io/docs[main documentation] or on the https://twitch4j.github.io/javadoc[Full Javadoc].

=== Support

images::https://discordapp.com/api/guilds/143001431388061696/embed.png?style=banner2[link=https://discord.gg/FQ5vgW3]
images::https://discordapp.com/api/guilds/325552783787032576/embed.png?style=banner2[link=https://discord.gg/8NXaEyV]

---

=== Quick Note:

This project provides multiple standalone modules you can use to interact with Twitch and related services.

=== Quick Start

Check out the https://twitch4j.github.io/docs/getting-started/installation/[Documentation]!

---

=== Modules

Project

* https://twitch4j.github.io/docs/components/authentication[Auth]
* https://twitch4j.github.io/docs/components/api[API]
* https://twitch4j.github.io/docs/components/chat[Chat (with API and Commands)]
* https://twitch4j.github.io/docs/components/pubsub[PubSub]
* https://twitch4j.github.io/docs/components/websub[WebSub]
* https://twitch4j.github.io/docs/components/eventsub[EventSub]
* https://twitch4j.github.io/docs/components/extensions[Extensions API]
* https://twitch4j.github.io/docs/components/graphql[GraphQL]

=== Problems

If you have problems using the *Twitch Java API*, then you are welcome to join the https://discord.gg/FQ5vgW3[discord server] to talk about it.

If you discover any issues/have feature requests, then please https://github.com/twitch4j/twitch4j/issues/new[open an issue here].

NOTE: Issue is not place for the question.
Please go to our https://discord.gg/FQ5vgW3[discord server] to ask your question.

=== Contributing

We welcome contributions to the library, be it new features, bug fixes, or even small enhancements.
Please do read the https://twitch4j.github.io/docs/contribution/[contributing guide] on the documentation site as it provides code guidelines and helpful tips for getting started.
By contributing, you are expected to abide by our https://twitch4j.github.io/docs/contribution/code-of-conduct[code of conduct] and agree to the license below.
Thank you again for your interest in improving Twitch4J!

=== Our websites

* https://twitch4j.github.io/[Main Website]
* https://twitch4j.github.io/docs[Main Documentation]
* https://twitch4j.github.io/javadoc[Full Javadoc]

=== License

Released under the https://github.com/twitch4j/twitch4j/blob/main/LICENSE[MIT license]
