name: Release
on:
  schedule:
    - cron: '0 22 * * 4/2' # deploy release every second friday on 10PM UTC

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{ github.repository.toLowerCase() === 'twitch4j/twitch4j' }} # runs only main repo - allows to skipping trigger from other repos
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - run: git push origin main # push to main repo
